### PR TITLE
Added Makefile.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by cbredesen** [comment]
Thanks for adding a Makefile! It was unsuccessful for me, however:

```
$ make
make: *** No rule to make target 'nickchange.so', needed by 'build'.  Stop.
```

The problem is a missing $ in the build target on line 14. With that chage, it works. Love to see this merged.

**Comment by ypid** [comment]
Thanks :+1:

**Comment by cbredesen** [comment]
Thank you!

**Comment by EionRobb** [comment]
Thanks for the Makefile. I'm sorry I didn't see this PR sooner :(

**Pull request merged**
